/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#f4f1e1",
        "on-primary-fixed-variant": "#5e4200",
        "on-tertiary-fixed-variant": "#0b513d",
        "secondary-fixed-dim": "#ffb77d",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        secondary: "#904d00",
        "inverse-on-surface": "#f5f1e1",
        "on-primary-container": "#6b4c00",
        "on-background": "#2f1500",
        "on-primary-fixed": "#271900",
        "surface-container": "#f2eede",
        "on-secondary-fixed": "#2f1500",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "tertiary-container": "#93d2b9",
        "on-error": "#ffffff",
        outline: "#837560",
        "inverse-surface": "#323126",
        "on-secondary-fixed-variant": "#6e3900",
        "primary-container": "#ffb800",
        primary: "#7c5800",
        "on-surface": "#1c1c13",
        "on-tertiary-fixed": "#002117",
        error: "#ba1a1a",
        "tertiary-fixed-dim": "#95d3ba",
        "surface-tint": "#7c5800",
        "surface-container-low": "#fcf8ec",
        "surface-container-high": "#ece8d9",
        "inverse-primary": "#ffba20",
        "on-tertiary-container": "#1b5c48",
        "surface-dim": "#dedacb",
        "primary-fixed-dim": "#ffba20",
        "primary-fixed": "#ffdea8",
        "secondary-container": "#fe932c",
        "surface-bright": "#fdf9e9",
        "on-tertiary": "#ffffff",
        surface: "#fdf9e9",
        background: "#fdf9e9",
        "tertiary-fixed": "#b0f0d6",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#ffdcc3",
        tertiary: "#2b6954",
        "on-secondary-container": "#663500",
        "on-surface-variant": "#514532",
        "surface-container-highest": "#e6e3d3",
        "outline-variant": "#d5c4ab",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "container-max": "1280px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        "body-lg": ["Plus Jakarta Sans"],
        "headline-sm": ["Libre Caslon Text"],
        "display-lg-mobile": ["Libre Caslon Text"],
        "body-md": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-md": ["Libre Caslon Text"],
        "display-lg": ["Libre Caslon Text"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg-mobile": [
          "36px",
          { lineHeight: "42px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};
